[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "tYKuFRz4agpQv4ZRDLUN3Bzfdfbkbzv7Tdg3ev2Ta7c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hackerman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
